name: Test and Check formatting
on: [push]

jobs:
# Disabling testing until I can get freetype compiling on CI
#    test:
#        name: Run zig test
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v2
#            - uses: goto-bus-stop/setup-zig@v1
#              with:
#                  version: 0.6.0
#            - name: Install SDL for native build
#              run: sudo apt-get install libsdl2-dev libfreetype-dev
#            - run: zig build all
    fmt:
        name: Check zig formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: goto-bus-stop/setup-zig@v1
              with:
                  version: 0.6.0
            - run: zig fmt --check build.zig ./src/ ./tools/
